package com.example.chatbotbackend;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.Map;

public class SendmessagesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {

    System.out.println(driver);
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void sendMessages() throws InterruptedException {
    System.setProperty("webdriver.chrome.driver", "chromedriver");
    driver = new ChromeDriver();
    driver.get("http://localhost:4200/");
    driver.manage().window().setSize(new Dimension(1440, 900));
    driver.findElement(By.cssSelector(".login-button:nth-child(1)")).click();
    Thread.sleep(1500);
    driver.findElement(By.id("comment")).click();
    Thread.sleep(1500);
    driver.findElement(By.id("comment")).sendKeys("hello");
    Thread.sleep(1500);
    driver.findElement(By.cssSelector(".btn")).click();
    Thread.sleep(1500);
    driver.findElement(By.id("comment")).click();
    Thread.sleep(1500);
    driver.findElement(By.id("comment")).sendKeys("bonjour");
    driver.findElement(By.cssSelector(".btn")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("comment")).click();
    driver.findElement(By.id("comment")).sendKeys("what services do you offer");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".container1:nth-child(2) > .img-responsive")).click();
    driver.findElement(By.cssSelector(".heading-contact-container > div:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".login-button:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".heading-contact-container > div:nth-child(3)")).click();
    driver.findElement(By.cssSelector("app-root")).click();
  }
}
