package com.example.chatbotbackend;// Generated by Selenium IDE

import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.HashMap;
import java.util.Map;
public class TestinteractionchatbotTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
//  @After
//  public void tearDown() {
//    driver.quit();
//  }
  @Test
  public void testinteractionchatbot() throws InterruptedException {
    driver.get("http://localhost:4200/");
    driver.manage().window().setSize(new Dimension(1440, 875));
    driver.findElement(By.cssSelector(".login-button:nth-child(1)")).click();
    driver.findElement(By.id("comment")).click();
    driver.findElement(By.id("comment")).sendKeys("bonjour");
    driver.findElement(By.cssSelector(".btn")).click();
    Thread.sleep(1000);
    driver.findElement(By.id("comment")).click();
    driver.findElement(By.id("comment")).sendKeys("hello");
    driver.findElement(By.cssSelector(".btn")).click();
//    driver.close();
  }
}
